[versions]
kotlin = "1.8.10"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = "io.gitlab.arturbosch.detekt:1.22.0"
ktlint = "org.jlleitschuh.gradle.ktlint:11.3.1"
pluginPublish = "com.gradle.plugin-publish:1.1.0"

[libraries]
junit4 = "junit:junit:4.13.2"
